version: "3.4"

services:
  mylogpt:
    build: .
    container_name: mylogpt
    restart: unless-stopped
    command: bundle exec ruby app.rb -s puma -e development -o 0.0.0.0
    depends_on:
      - mylogpt_redis
    environment:
      - REDIS_URL=redis://mylogpt-redis:6379
      - PG_HOST=mylogpt-postgres
    ports:
      - 4567:4567
    env_file: .env

  mylogpt_sidekiq:
    build: .
    container_name: mylogpt-sidekiq
    restart: unless-stopped
    command: bundle exec sidekiq -r ./app.rb
    depends_on:
      - mylogpt_redis
    environment:
      - REDIS_URL=redis://mylogpt-redis:6379
    env_file: .env

  mylogpt_redis:
    image: redis
    container_name: mylogpt-redis
    restart: unless-stopped

  # an endpoint to receive webhook payloads
  mylogpt_echo:
    image: mendhak/http-https-echo:29
    container_name: mylogpt-echo
    restart: unless-stopped

  mylogpt_postgres:
    container_name: mylogpt-postgres
    image: ankane/pgvector
    restart: unless-stopped
    user: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mylogpt
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
