name: Docker

on:
  - push
  - pull_request

env:
  DOCKER_URL: docker.jsch.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login $DOCKER_URL -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Set branch name in env variable
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_URL }}/mylogpt:${{ env.BRANCH }}
          build-args: |
            BRANCH=${{ env.BRANCH }}
